// Generated by gencpp from file posecnn_pytorch/BBox.msg
// DO NOT EDIT!


#ifndef POSECNN_PYTORCH_MESSAGE_BBOX_H
#define POSECNN_PYTORCH_MESSAGE_BBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace posecnn_pytorch
{
template <class ContainerAllocator>
struct BBox_
{
  typedef BBox_<ContainerAllocator> Type;

  BBox_()
    : x1(0)
    , y1(0)
    , x2(0)
    , y2(0)  {
    }
  BBox_(const ContainerAllocator& _alloc)
    : x1(0)
    , y1(0)
    , x2(0)
    , y2(0)  {
  (void)_alloc;
    }



   typedef int32_t _x1_type;
  _x1_type x1;

   typedef int32_t _y1_type;
  _y1_type y1;

   typedef int32_t _x2_type;
  _x2_type x2;

   typedef int32_t _y2_type;
  _y2_type y2;





  typedef boost::shared_ptr< ::posecnn_pytorch::BBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::posecnn_pytorch::BBox_<ContainerAllocator> const> ConstPtr;

}; // struct BBox_

typedef ::posecnn_pytorch::BBox_<std::allocator<void> > BBox;

typedef boost::shared_ptr< ::posecnn_pytorch::BBox > BBoxPtr;
typedef boost::shared_ptr< ::posecnn_pytorch::BBox const> BBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::posecnn_pytorch::BBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::posecnn_pytorch::BBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::posecnn_pytorch::BBox_<ContainerAllocator1> & lhs, const ::posecnn_pytorch::BBox_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::posecnn_pytorch::BBox_<ContainerAllocator1> & lhs, const ::posecnn_pytorch::BBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace posecnn_pytorch

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::posecnn_pytorch::BBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::posecnn_pytorch::BBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::posecnn_pytorch::BBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::posecnn_pytorch::BBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::posecnn_pytorch::BBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::posecnn_pytorch::BBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::posecnn_pytorch::BBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01b404007f6687249fa0f27eea3c1daf";
  }

  static const char* value(const ::posecnn_pytorch::BBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01b404007f668724ULL;
  static const uint64_t static_value2 = 0x9fa0f27eea3c1dafULL;
};

template<class ContainerAllocator>
struct DataType< ::posecnn_pytorch::BBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "posecnn_pytorch/BBox";
  }

  static const char* value(const ::posecnn_pytorch::BBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::posecnn_pytorch::BBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x1\n"
"int32 y1\n"
"int32 x2\n"
"int32 y2\n"
;
  }

  static const char* value(const ::posecnn_pytorch::BBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::posecnn_pytorch::BBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::posecnn_pytorch::BBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::posecnn_pytorch::BBox_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSECNN_PYTORCH_MESSAGE_BBOX_H
