// Generated by gencpp from file posecnn_pytorch/DetectionList.msg
// DO NOT EDIT!


#ifndef POSECNN_PYTORCH_MESSAGE_DETECTIONLIST_H
#define POSECNN_PYTORCH_MESSAGE_DETECTIONLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <posecnn_pytorch/Detection.h>

namespace posecnn_pytorch
{
template <class ContainerAllocator>
struct DetectionList_
{
  typedef DetectionList_<ContainerAllocator> Type;

  DetectionList_()
    : detections()  {
    }
  DetectionList_(const ContainerAllocator& _alloc)
    : detections(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::posecnn_pytorch::Detection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::posecnn_pytorch::Detection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::posecnn_pytorch::DetectionList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::posecnn_pytorch::DetectionList_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionList_

typedef ::posecnn_pytorch::DetectionList_<std::allocator<void> > DetectionList;

typedef boost::shared_ptr< ::posecnn_pytorch::DetectionList > DetectionListPtr;
typedef boost::shared_ptr< ::posecnn_pytorch::DetectionList const> DetectionListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::posecnn_pytorch::DetectionList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::posecnn_pytorch::DetectionList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::posecnn_pytorch::DetectionList_<ContainerAllocator1> & lhs, const ::posecnn_pytorch::DetectionList_<ContainerAllocator2> & rhs)
{
  return lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::posecnn_pytorch::DetectionList_<ContainerAllocator1> & lhs, const ::posecnn_pytorch::DetectionList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace posecnn_pytorch

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::posecnn_pytorch::DetectionList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::posecnn_pytorch::DetectionList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::posecnn_pytorch::DetectionList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::posecnn_pytorch::DetectionList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::posecnn_pytorch::DetectionList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::posecnn_pytorch::DetectionList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::posecnn_pytorch::DetectionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85de709e8e4b1999046a6c2a4f7beaec";
  }

  static const char* value(const ::posecnn_pytorch::DetectionList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85de709e8e4b1999ULL;
  static const uint64_t static_value2 = 0x046a6c2a4f7beaecULL;
};

template<class ContainerAllocator>
struct DataType< ::posecnn_pytorch::DetectionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "posecnn_pytorch/DetectionList";
  }

  static const char* value(const ::posecnn_pytorch::DetectionList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::posecnn_pytorch::DetectionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "posecnn_pytorch/Detection[] detections\n"
"\n"
"================================================================================\n"
"MSG: posecnn_pytorch/Detection\n"
"string name\n"
"float32 score\n"
"posecnn_pytorch/BBox roi\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: posecnn_pytorch/BBox\n"
"int32 x1\n"
"int32 y1\n"
"int32 x2\n"
"int32 y2\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::posecnn_pytorch::DetectionList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::posecnn_pytorch::DetectionList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::posecnn_pytorch::DetectionList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::posecnn_pytorch::DetectionList_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::posecnn_pytorch::Detection_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSECNN_PYTORCH_MESSAGE_DETECTIONLIST_H
