// Generated by gencpp from file posecnn_pytorch/Detection.msg
// DO NOT EDIT!


#ifndef POSECNN_PYTORCH_MESSAGE_DETECTION_H
#define POSECNN_PYTORCH_MESSAGE_DETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <posecnn_pytorch/BBox.h>
#include <geometry_msgs/PoseStamped.h>

namespace posecnn_pytorch
{
template <class ContainerAllocator>
struct Detection_
{
  typedef Detection_<ContainerAllocator> Type;

  Detection_()
    : name()
    , score(0.0)
    , roi()
    , pose()  {
    }
  Detection_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , score(0.0)
    , roi(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _score_type;
  _score_type score;

   typedef  ::posecnn_pytorch::BBox_<ContainerAllocator>  _roi_type;
  _roi_type roi;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::posecnn_pytorch::Detection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::posecnn_pytorch::Detection_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_

typedef ::posecnn_pytorch::Detection_<std::allocator<void> > Detection;

typedef boost::shared_ptr< ::posecnn_pytorch::Detection > DetectionPtr;
typedef boost::shared_ptr< ::posecnn_pytorch::Detection const> DetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::posecnn_pytorch::Detection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::posecnn_pytorch::Detection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::posecnn_pytorch::Detection_<ContainerAllocator1> & lhs, const ::posecnn_pytorch::Detection_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.score == rhs.score &&
    lhs.roi == rhs.roi &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::posecnn_pytorch::Detection_<ContainerAllocator1> & lhs, const ::posecnn_pytorch::Detection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace posecnn_pytorch

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::posecnn_pytorch::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::posecnn_pytorch::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::posecnn_pytorch::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::posecnn_pytorch::Detection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::posecnn_pytorch::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::posecnn_pytorch::Detection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::posecnn_pytorch::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4be425bb4306d8ff3be362c5aaed7540";
  }

  static const char* value(const ::posecnn_pytorch::Detection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4be425bb4306d8ffULL;
  static const uint64_t static_value2 = 0x3be362c5aaed7540ULL;
};

template<class ContainerAllocator>
struct DataType< ::posecnn_pytorch::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "posecnn_pytorch/Detection";
  }

  static const char* value(const ::posecnn_pytorch::Detection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::posecnn_pytorch::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float32 score\n"
"posecnn_pytorch/BBox roi\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: posecnn_pytorch/BBox\n"
"int32 x1\n"
"int32 y1\n"
"int32 x2\n"
"int32 y2\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::posecnn_pytorch::Detection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::posecnn_pytorch::Detection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.score);
      stream.next(m.roi);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::posecnn_pytorch::Detection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::posecnn_pytorch::Detection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roi: ";
    Printer< ::posecnn_pytorch::BBox_<ContainerAllocator> >::stream(s, indent + "  ", v.roi);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSECNN_PYTORCH_MESSAGE_DETECTION_H
